version: '3'
services:
  database_mysql:
    image: mysql:5.7
    restart: always
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: marketapi
      MYSQL_DATABASE: marketplace
      MYSQL_USER: marketplace
      MYSQL_PASSWORD: marketapi
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - "database_mysql"